Cinema.Web/Controllers/ShowsController.cs
using Cinema.Data.Models;
using Cinema.Data.Models.DTOs;
using Cinema.Data.Models.Tables.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Cinema.Web.Controllers
{
    public class ShowsController : Controller
    {
        private readonly CinemaDbContext _context;

        public ShowsController(CinemaDbContext service)
        {
            _context = service;
        }

        // GET: Shows/Edit/5
        public async Task<IActionResult> Edit(Int32 id)
        {
            var show = await _context.Shows.FindAsync(id);

            if (show == null)
                return NotFound();

            var reserveSeatDTO = SeatReserve.Create(show);

            ViewData["Title"] = show.Movie.Title.ToString();
            ViewData["Start"] = show.Start.ToString();

            return View(reserveSeatDTO);
        }

        // POST: Shows/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Int32 id, SeatReserve dto)
        {
            if (id != dto.ShowId)
                return NotFound();

            if (dto.Seats.Where(s => s.ToReserve).Count() > 6)
                return await Edit(id);

            if (ModelState.IsValid)
            {
                try
                {
                    var seatIds = dto.Seats
                        .Where(s => s.ToReserve && !s.Reserved)
                        .Select(s => s.Id);

                    var toReserve = _context.Seats.Where(s => seatIds.Contains(s.Id));

                    if (toReserve.Any(s => s.Status != Status.Free))
                        return await Edit(id);

                    await _context.Seats.Where(s => seatIds.Contains(s.Id)).ForEachAsync(p =>
                        (p.Status, p.ReservantName, p.ReservantPhoneNumber) =
                            (Status.Reserved, dto.Name, dto.PhoneNumber));
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!(await ShowExistsAsync(dto.ShowId)))
                        return NotFound();
                    else
                        throw;
                }

                return RedirectToAction("Index", "Movies");
            }
            return await Edit(id);
        }

        private async Task<Boolean> ShowExistsAsync(Int32 id)
        {
            return (await _context.Shows.FindAsync(id)) != null;
        }
    }
}

Cinema.Web/Views/Shows/Create.cshtml
@model Cinema.Data.Models.Tables.Show

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Show</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Start" class="control-label"></label>
                <input asp-for="Start" class="form-control" />
                <span asp-validation-for="Start" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MovieId" class="control-label"></label>
                <select asp-for="MovieId" class ="form-control" asp-items="ViewBag.MovieId"></select>
            </div>
            <div class="form-group">
                <label asp-for="HallId" class="control-label"></label>
                <select asp-for="HallId" class ="form-control" asp-items="ViewBag.HallId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Cinema.Web/Views/Shows/Delete.cshtml
@model Cinema.Data.Models.Tables.Show

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Show</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Start)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Start)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Movie.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hall)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hall.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Cinema.Web/Views/Shows/Details.cshtml
@model Cinema.Data.Models.Tables.Show

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Show</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Start)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Start)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Movie.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hall)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hall.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Cinema.Web/Views/Shows/Edit.cshtml
@model SeatReserve

<h1>Helyfoglalás</h1>
@{
    var title = ViewData["Title"]!.ToString();
    var start = ViewData["Start"]!.ToString();
}
<h4>@Html.DisplayFor(_ => title) - @Html.DisplayFor(_ => start)</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("Edit"))
        {
            @Html.HiddenFor(m => m.ShowId)
            <div class="row g-2">
                <div class="col-md-6 form-floating">
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                    @Html.LabelFor(m => m.Name)
                    @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-6 form-floating">
                    @Html.EditorFor(m => m.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.LabelFor(m => m.PhoneNumber)
                    @Html.ValidationMessageFor(m => m.PhoneNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <table class="seat-table table">
                <tbody>
                    @{
                        var rowCount = Model.HallSize.RowCount;
                        var columnCount = Model.HallSize.ColumnCount;
                    }
                    @for (Int32 i = 0; i < rowCount; i++)
                    {
                        <tr>
                            <td>
                                <b>@(i + 1)</b>
                            </td>
                            @for (Int32 j = 0; j < columnCount; j++)
                            {
                                var index = i * columnCount + j;
                                <td>
                                    @Html.HiddenFor(m => m.Seats[index].Id)
                                    @Html.CheckBoxFor(m => m.Seats[index].ToReserve,
                                             Model.Seats[index].Reserved
                                             ? new
                                             {
                                                 @class = "btn-check",
                                                 @disabled = ""
                                             }
                                             : new
                                             {
                                                 @class = "btn-check seat",
                                                 @onclick = "checkSeats()"
                                             })
                                    @Html.LabelFor(m => m.Seats[index].ToReserve,
                                             (j + 1).ToString(),
                                             new
                                             {
                                                 @class = "btn btn-outline-" +
                                             (Model.Seats[index].Reserved ? "secondary" : "primary")
                                             })
                                </td>
                            }
                            <td>
                                <b>@(i + 1)</b>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
            <div class="row form-group">
                <div class="col-md-6">
                    @Html.ActionLink("Vissza a mai műsorajánlathoz", "Index", "Movies",
                             new(), new { @class = "btn btn-secondary" })
                </div>
                <div class="col-md-6">
                    <input type="submit" value="Helyfoglalás véglegesítése"
                           class="btn btn-primary" />
                </div>
            </div>
        }
    </div>
</div>

<script src="~/js/showsEdit.js"></script>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Cinema.Web/Views/Shows/Index.cshtml
@model IEnumerable<ShowIndex>

<h1>Mai műsorajánlat</h1>

<table class="table">
    <thead>
        <tr>
            <th>Cím</th>
            <th>Kezdés időpontja</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(_ => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(_ => item.Start)
                </td>
                <td>
                    @Html.ActionLink("Foglalás", "Edit", "Shows",
                             new { @id = $"{item.Id}" },
                             item.FreeSeatCount <= 0
                             ? new { @class = "btn btn-primary" }
                             : new { @class = "btn btn-primary", @disabled = "" })
                </td>
            </tr>
        }
    </tbody>
</table>